---
- name: Add custom strongSwan repo
  apt_repository:
    repo: 'ppa:develer/strongswan'

- name: Install strongSwan
  apt:
    name: strongswan
    state: present
    update_cache: yes

- name: Change sysctl
  sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    state: present
    reload: yes
    sysctl_set: yes
  with_items:
  - { name: net.ipv4.ip_forward, value: 1 }
  - { name: net.ipv4.conf.all.rp_filter, value: 0 }
  - { name: net.ipv4.conf.all.disable_policy, value: 1 }
  - { name: net.ipv4.conf.default.rp_filter, value: 0 }
  - { name: net.ipv4.conf.default.disable_policy, value: 1 }
  - { name: net.ipv4.conf.eth0.disable_xfrm, value: 1 }

- name: Deploy ipsec.conf
  template: src=ipsec.conf.j2 dest=/etc/ipsec.conf
  notify: restart strongSwan

- name: Deploy charon.conf
  template: src=charon.conf.j2 dest=/etc/strongswan.d/charon.conf
  notify: restart strongSwan

- name: Deploy charon kernel-link plugin
  template: src=kernel-netlink.conf.j2 dest=/etc/strongswan.d/charon/kernel-netlink.conf
  notify: restart strongSwan

- name: Deploy ipsec.secrets
  template: src=ipsec.secrets.j2 dest=/etc/ipsec.secrets
  notify: restart strongSwan

- name: Deploy ipsec-vti.sh
  template: src=ipsec-vti.sh.j2 dest=/etc/strongswan.d/ipsec-vti.sh
  notify: restart strongSwan

- name: Make ipsec-vti.sh exacutable
  file:
    path: /etc/strongswan.d/ipsec-vti.sh
    mode: "u=rwx,g=rwx,o-rwx"

- name: Enable and start strongSwan
  service:
    name: strongswan
    state: started
    enabled: yes